---
- name: quick ini file parse test
  hosts: localhost
  gather_facts: false
  vars:
  tasks:
  - name: find all of the repo sections
    ansible.builtin.shell: cat ciq.repo | grep -o '\[.*\]' | tr -d '[]'
    register: section_list

  - name: debug section_list
    var: section_list


  - name: debug
    ansible.builtin.debug:
      msg: "{{ lookup('ansible.builtin.ini', 'enabled', section='internal-8-tools', file='ciq.repo') }}"
