---
- name: Perform mountain V2 migration
  hosts: mtn-hosts
  gather_facts: false
  vars:
    # This is the version that the CIQ binary should at a minimum be at
    req_ciq_version: 1.0.1
  
    # This is the access key created in mountain to authenticate the subscription
    # This key should be maintained securely in a vault or securely within Ascender
    mtn_access_key: xzy123

    #files to be manually deleted
    remove_files: 
      - /etc/yum.repos.d/ciq.repo
      - /etc/ciq.cfg

    # repo file for parsing to reenable packages
    repo_file: /etc/yum.repos.d/ciq.repo

  tasks:
  - name: Check which version of ciq binary is present
    when: presence.changed is true
    ansible.builtin.shell: ciq -v | awk '{print $3 }' | sed 's/^v//' | cut -d'-' -f1
    register: ciq_version

  - name: find all of the repo sections from the repo file
    ansible.builtin.shell: "cat {{ repo_file }} | grep -o '\\[.*\\]' | tr -d '[]'"
    register: section_list

  - name: make backup of repo file
    ansible.builtin.shell: "cat {{ repo_file }} > {{ repo_file }}.old"

  ##Block start - remove old ciq binary if too old
  - name: Block to remove old binary and repo
    when: ciq_version is defined and ciq_version is version(req_ciq_version, '<')
    block:
    - name: Remove ciq binary
      ansible.builtin.dnf:
        name:
          - ciq
        state: absent

    - name: Remove old repos
      ansible.builtin.dnf:
        name:
          - "https://repo.ciq.co/public/ciq-public-release.rpm"
        state: absent
    
    - name: Remove files manually
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop: "{{ remove_files }}"

  ##Block stop - remove old ciq binary if too old
      
  ##Block start - install new ciq binary
  - name: Block to install new repo/binary and add keys
#    when: (ciq_version is defined and ciq_version is version(req_ciq_version, '<'))
    block:

    - name: Install ciq repos
      ansible.builtin.dnf:
        name:
          - "https://repository.ciq.com/ciq-public-release.rpm"
        disable_gpg_check: true
        state: present

    - name: Install ciq binary
      ansible.builtin.dnf:
        name:
          - ciq
        state: latest

    - name: Enroll in the CIQ CLI using access key
      ansible.builtin.shell: "ciq enroll {{ mtn_access_key }}"

    - name: Enable the subscription
      when: lookup('ansible.builtin.ini', 'enabled', section=item, file='/etc/yum.repos.d/ciq.repo.old') == "1"
      ansible.builtin.shell: "ciq dnf enable {{ item }}"
      loop: "{{ section_list.stdout_lines }}"
  ##Block stop - install new ciq binary

#  - name: Update all packages on the system
#    ansible.builtin.dnf:
#      name: "*"
#      state: latest
