---
- name: Perform package update with LTS support
  hosts: lts_demo
  gather_facts: false
  vars:
    # This is the version that the CIQ binary should at a minimum be at
    req_ciq_version: .0.0.2
  
    # This is the lts version you are locking to
    lts_version: lts-8.6

    # This is the access key created in mountain to authenticate the subscription
    # This key should be maintained securely in a vault or securely within Ascender
    mtn_access_key: xzy123

    ciq_cfg_path: /etc/ciq.cfg

  tasks:
  - name: Search to see if LTS is already configured
    when: hostvars[inventory_hostname].lts_version is defined
    ansible.builtin.lineinfile:
      path: "{{ ciq_cfg_path }}"
      #line: "{{ lts_version }}"
      regexp: ".*{{ lts_version }}.*"
      #state: present
      state: absent
    check_mode: yes
    register: presence
#    failed_when: presence is changed

  - name: Check which version of ciq binary is present
    when: presence.changed is true
    ansible.builtin.shell: ciq -v | awk '{print $3 }'
    register: ciq_version

  ##Block start - remove old ciq binary if too old
  - name: Block to remove old binary and repo
    when: ciq_version is defined and ciq_version is version(req_ciq_version, '<')
    block:
    - name: Remove ciq binary
      ansible.builtin.dnf:
        name:
          - ciq
        state: absent

    - name: Remove old repos
      ansible.builtin.dnf:
        name:
          - "https://repo.ciq.co/public/ciq-public-release.rpm"
        state: absent
  ##Block stop - remove old ciq binary if too old
      
  ##Block start - install new ciq binary
  - name: Block to install new repo/binary and add keys
    when: presence.changed is false or (ciq_version is defined and ciq_version is version(req_ciq_version, '<'))
    block:

    - name: Install ciq repos
      ansible.builtin.dnf:
        name:
          - "https://repository.ciq.com/ciq-public-release.rpm"
        disable_gpg_check: true
        state: present

    - name: Install ciq binary
      ansible.builtin.dnf:
        name:
          - ciq
        state: present

    - name: Enroll in the CIQ CLI using access key
      ansible.builtin.shell: "ciq enroll --access-key {{ mtn_access_key }}"

    - name: Enable the subscription
      ansible.builtin.shell: "ciq enable --key {{ lts_version }}"
  ##Block stop - install new ciq binary

#  - name: Update all packages on the system
#    ansible.builtin.dnf:
#      name: "*"
#      state: latest
